# Generated by Django 5.2.11 on 2026-02-12 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('total_distance_miles', models.FloatField()),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('route_polyline', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('rack_id', models.IntegerField(blank=True, null=True)),
                ('retail_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_geocoded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='route_fuels_state_5fe3c6_idx'), models.Index(fields=['retail_price'], name='route_fuels_retail__2f5728_idx'), models.Index(fields=['latitude', 'longitude'], name='route_fuels_latitud_bd5405_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.IntegerField()),
                ('miles_from_start', models.FloatField()),
                ('gallons_filled', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.fuelstation')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stops', to='route.routerequest')),
            ],
        ),
    ]
