# Generated by Django 5.2.11 on 2026-02-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstop',
            name='distance_from_route_miles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routerequest',
            name='route_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='routerequest',
            name='vehicle_mpg',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='routerequest',
            name='vehicle_range_miles',
            field=models.FloatField(default=500),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='is_geocoded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='routerequest',
            index=models.Index(fields=['route_hash'], name='route_route_route_h_6c2606_idx'),
        ),
        migrations.AddConstraint(
            model_name='fuelstop',
            constraint=models.UniqueConstraint(fields=('route', 'stop_order'), name='unique_stop_order_per_route'),
        ),
    ]
